import type { Metadata } from "next";
import { PageShell } from "@/components/layout/PageShell";
import { MarketingIntro } from "@/components/marketing/Marketing";
import { BookForm } from "@/components/forms/BookForm";
import { StoryJourney } from "@/components/stories/StoryJourney";
import styles from "@/components/marketing/Marketing.module.css";
export const metadata: Metadata={
  alternates: { canonical: "/campaigns/virtual-ai-employees" },title:{absolute:"Put One Workflow to Work | Maslow AI"},description:"Connect your information, prepare a useful draft, and keep the right human decision. Start a scoped workflow implementation with Maslow."};
const steps=[
{id:"request",label:"The request",title:"A familiar task arrives.",body:"An intake request, document review, or client response needs information from more than one place.",items:[{label:"Inbox",detail:"A new request"},{label:"Sources",detail:"Relevant documents"},{label:"Owner",detail:"The person accountable"}],result:"An agreed task and its source boundary.",status:"ILLUSTRATIVE WORKFLOW"},
{id:"prepare",label:"The preparation",title:"Let the source work happen together.",body:"A scoped agent workflow gathers the material, drafts an answer, and points out the questions it cannot resolve.",items:[{label:"Find",detail:"Scoped retrieval"},{label:"Draft",detail:"Sources and assumptions"},{label:"Flag",detail:"Missing information"}],result:"A draft your reviewer can inspect.",status:"ILLUSTRATIVE WORKFLOW"},
{id:"review",label:"The decision",title:"A person decides what leaves.",body:"Your reviewer checks the draft and sources. Sending, changing records, or other consequential actions follow the agreed approval path.",items:[{label:"Review",detail:"The named owner"},{label:"Approve",detail:"An explicit decision"},{label:"Record",detail:"A trace of the work"}],result:"A controlled result and a starting point for evaluation.",status:"ILLUSTRATIVE WORKFLOW"}
] as const;
export default function WorkflowCampaign(){return <PageShell footer="compact"><MarketingIntro eyebrow="A WORKFLOW IMPLEMENTATION / START SMALL" title="Give one recurring task a better way through." body="We connect the information, tools, and review step around a task your team already does. You can begin with your existing systems; a new operating system is not a requirement." secondaryHref="#book" secondaryLabel="Request a conversation" /><StoryJourney id="workflow-example" eyebrow="FROM REQUEST TO REVIEW" title="The preparation changes. Your judgment stays involved." description="An illustrative workflow for a professional services team. The implementation and acceptance criteria are scoped with your people." variant="workflow" steps={steps} afterHref="#book" afterLabel="Discuss your own workflow" /><section className={styles.section} id="book"><div className={styles.grid}><div><p className="eyebrow">LET’S FIND A STARTING POINT</p><h2>Bring one task to the conversation.</h2><p className={styles.note}>We agree scope, fees, and an initial test before paid implementation. There is no automatic deployment or fixed delivery promise attached to this form.</p></div><BookForm ctaLabel="REQUEST A WORKING SESSION" /></div></section></PageShell>}
