import type { StoryJourneyProps } from "@/components/stories/StoryJourney";
export const manufacturingStory: StoryJourneyProps["steps"] = [
 { id: "find", label: "Find the drawing", title: "Start with the right revision.", body: "A supervisor needs a drawing from a past job. A scoped knowledge system can locate candidate files and surface their source and revision for review.", items: [{label:"Network drive",detail:"Drawings and job folders"},{label:"Retrieve",detail:"Job and revision context"},{label:"Supervisor",detail:"Checks the source"}], result: "A source-linked answer to check before it reaches the floor.", status:"ILLUSTRATIVE WORKFLOW" },
 { id: "quote", label: "Prepare the quote", title: "Give the estimator a better starting point.", body: "An agent gathers comparable jobs, material references, and the missing information. The estimator reviews assumptions and retains authority over the final quote.", items: [{label:"Request",detail:"Customer requirements"},{label:"Preparation",detail:"Comparable jobs and gaps"},{label:"Estimator",detail:"Judgment and approval"}],result:"A draft with sources and open questions, ready for an experienced person.",status:"ILLUSTRATIVE WORKFLOW" },
 { id: "report", label: "Assemble the report", title: "Bring the numbers into the same conversation.", body: "A connected workflow can gather agreed fields from the ERP and job tracker, highlight missing inputs, and prepare a report for a supervisor to review.",items:[{label:"Systems",detail:"ERP and job tracker"},{label:"Assemble",detail:"Selected reporting fields"},{label:"Review",detail:"Supervisor owns release"}],result:"A reviewable report with the source work already organized.",status:"ILLUSTRATIVE WORKFLOW" },
];
export const dataPathStory: StoryJourneyProps["steps"] = [
 {id:"sources",label:"Source",title:"Start with the information in scope.",body:"Your document library or business system remains the source. The implementation defines which records a connector may read and how access is revoked.",items:[{label:"Your environment",detail:"Files and business records"},{label:"Access scope",detail:"Selected sources"},{label:"Connector",detail:"Configured credentials"}],result:"A source and permissions register for the agreed workflow.",status:"DEPLOYMENT DESIGN"},
 {id:"processing",label:"Process",title:"Know where the work runs.",body:"Retrieval can run on local infrastructure while a chosen external model receives a selected excerpt. A fully local route needs a suitable local model and separately reviewed tool connections.",items:[{label:"Local services",detail:"Search and storage"},{label:"Routing",detail:"Local or external model"},{label:"Provider",detail:"Account and retention terms"}],result:"A documented data path, including any external service boundary.",status:"DEPLOYMENT DESIGN"},
 {id:"action",label:"Act",title:"Keep the consequential decision visible.",body:"The workflow defines when a person reviews a draft, approves an action, or stops the process. Tracing and access controls must be tested in the tools being used.",items:[{label:"Draft",detail:"An agent prepares"},{label:"Approval",detail:"The named reviewer"},{label:"Record",detail:"Action and retained evidence"}],result:"A tested review boundary and a record suited to the scope.",status:"DEPLOYMENT DESIGN"},
];
