import type { StoryJourneyProps } from "@/components/stories/StoryJourney";

export const startingPoints = [
  { id: "discover", label: "Find the opportunity", title: "Start with the work worth improving.", body: "Your team sees the friction every day. We map a handful of recurring tasks, check the information they need, and choose a useful first test.", items: [{ label: "People", detail: "The workflow owner" }, { label: "Work", detail: "One recurring task" }, { label: "Decision", detail: "Where to begin" }], result: "A ranked opportunity brief and a scoped next step.", status: "PAID DISCOVERY", href: "/plan-workflow", proof: "Map a workflow" },
  { id: "setup", label: "Set up the foundation", title: "Make room for the tools your team uses.", body: "We configure an evaluation workspace, agent access, shared conventions, and suitable services. Use the Maslow AI-OS preview where it fits, or build on your existing Linux infrastructure.", items: [{ label: "Workspace", detail: "A suitable environment" }, { label: "Agents", detail: "Accounts and permissions" }, { label: "Handover", detail: "Setup your team understands" }], result: "A configured starting environment with documented setup and boundaries.", status: "SCOPED SETUP", href: "/ai-os", proof: "Explore the OS preview" },
  { id: "knowledge", label: "Connect your knowledge", title: "Turn the information you have into answers you can use.", body: "We connect selected folders, network drives, SharePoint libraries, and business sources. Retrieval and knowledge graphs are evaluated against the questions your team needs to answer.", items: [{ label: "Sources", detail: "Files, documents, images" }, { label: "Knowledge", detail: "Search and relationships" }, { label: "Answer", detail: "Sources you can inspect" }], result: "A knowledge system for an agreed scope, with retrieval checks and a source register.", status: "CLIENT IMPLEMENTATION", href: "/case-studies/agenthub", proof: "See the contract-review implementation" },
  { id: "workflows", label: "Build one workflow", title: "Help a recurring task reach the person who decides.", body: "We connect information, agent tools, and the review step around a bounded task. Start with preparing a report, reviewing a document, or assembling the information behind a quote.", items: [{ label: "Prepare", detail: "Gather and draft" }, { label: "Review", detail: "A named human decision" }, { label: "Learn", detail: "Record the result" }], result: "A tested workflow, agreed acceptance criteria, and a plan for operating it.", status: "CLIENT IMPLEMENTATION", href: "/case-studies/infinite-ai-os", proof: "See the manufacturing engagement" },
] as const;

export const deliverySteps: StoryJourneyProps["steps"] = [
  { id: "discover", label: "Understand", title: "Meet the work where it happens.", body: "We start with the people doing the task, the sources they use, and the decisions that matter. Existing systems shape the scope.", items: [{ label: "Observe", detail: "The current task" }, { label: "Map", detail: "Sources and owners" }, { label: "Choose", detail: "A useful test" }], result: "A scope and a decision to proceed, refine, or stop." },
  { id: "validate", label: "Prove", title: "Test the difficult part early.", body: "A focused proof uses representative information and questions. We agree what good looks like before judging the result.", items: [{ label: "Sample", detail: "Relevant information" }, { label: "Test", detail: "An agreed baseline" }, { label: "Review", detail: "Results and gaps" }], result: "Evidence to decide whether further implementation makes sense." },
  { id: "build", label: "Connect", title: "Put the pieces around one workflow.", body: "We configure the selected knowledge, tools, permissions, and review steps. Your team sees the work take shape and tests the result.", items: [{ label: "Knowledge", detail: "Scoped sources" }, { label: "Workflow", detail: "Tools and approvals" }, { label: "Acceptance", detail: "Tested with your team" }], result: "An implemented scope with documented limits and acceptance evidence." },
  { id: "handover", label: "Make it yours", title: "Leave your team able to use it.", body: "We work through operation, changes, and recovery with the people taking it on. Training and ongoing support are scoped to what your team needs.", items: [{ label: "Enable", detail: "Practical training" }, { label: "Document", detail: "Runbooks and ownership" }, { label: "Operate", detail: "Your team or scoped support" }], result: "A handover, clear responsibility, and a maintenance decision." },
];
