import Link from "next/link";
import { EnvironmentChooser } from "@/components/marketing/EnvironmentChooser";
import type { Metadata } from "next";
import { PageShell } from "@/components/layout/PageShell";
import { MarketingIntro, NextStep } from "@/components/marketing/Marketing";
import styles from "@/components/marketing/Marketing.module.css";
export const metadata: Metadata = { title: { absolute: "Maslow AI-OS | Explore the Development Preview" }, description: "A free, customizable Linux workspace for AI work, in development. See agent setup, workspace capabilities, evaluation requirements, and what Maslow can help connect.", alternates: { canonical: "/ai-os" } };
const capabilities = [
 ["Your Linux workspace", "Existing source capability", "Omarchy-based tiling, terminal layouts, developer tools, themes, and customization. Use dedicated workspaces to keep agents, sources, and review work together."],
 ["Codex, Claude Code, Hermes", "Setup paths in development", "Agent installation, provider sign-in, readiness, and permissions are separate steps. The preview is being tested against these tools."],
 ["Skills and second brain", "Early foundation", "Shared operational skills and a place for notes are starting points. Organization-wide memory and cross-agent retrieval require configured services and access boundaries."],
 ["Maslow Hub", "Development candidate", "A place for setup, connections, and the tool catalog. Availability depends on the build and integration."],
 ["Knowledge and connections", "Client implementation", "Drive and SharePoint ingestion, vector search, knowledge graphs, MCP connections, and legacy-system workflows are scoped around your organization."],
 ["Observability", "Experimental integration", "Tracing must be configured and verified for each supported harness. A single dashboard is not evidence that every agent is instrumented."],
];
export default function AiOsPage() { return <PageShell footer="full"><MarketingIntro eyebrow="MASLOW AI-OS / DEVELOPMENT PREVIEW" title="A workspace to make your own." body="Maslow AI-OS is a free Linux environment being built around the way people work with AI. Start with your preferred agents and a customizable desktop, then connect the knowledge and services your work needs." secondaryHref="/#workspace" secondaryLabel="Explore the workspace" />
<EnvironmentChooser />
<section className={styles.section} id="preview"><div className={styles.note}><strong>In development.</strong> A public download is not available through this website. The current work is an evaluation candidate; a stable signed public release and broad hardware acceptance remain open milestones.</div><div className={styles.grid}><article className={styles.row}><p className="eyebrow">FOR AN EVALUATION</p><h2>A technical champion. A concrete task.</h2><p>The preview suits someone comfortable with Linux and development-stage software, with a dedicated test machine and time for configuration.</p><p>Current installer work targets x86_64 hardware. There is no broad supported-hardware matrix yet.</p></article><article className={styles.row}><p className="eyebrow">FOR YOUR ORGANIZATION</p><h2>Build on what you already use.</h2><p>Maslow also implements knowledge systems and workflows on existing infrastructure, including Ubuntu. Your wider team can keep using its existing business tools.</p><p>Organization services need their own hosting, identity, permissions, and availability decisions.</p></article></div></section>
<section className={styles.section} id="capabilities"><p className="eyebrow">THE FOUNDATION, PIECE BY PIECE</p><h2>Know what you’re evaluating.</h2><table className={styles.table}><thead><tr><th scope="col">Area</th><th scope="col">Current boundary</th><th scope="col">What it means</th></tr></thead><tbody>{capabilities.map(([name,status,body])=><tr key={name}><td>{name}</td><td>{status}</td><td>{body}</td></tr>)}</tbody></table><p>Development summary used for this September 2026 website preview. Each evaluation starts with the build and supported scope confirmed together.</p></section>
<section className={styles.section}><div className={styles.grid}><article className={styles.row}><h3>Free OS. Separate operating costs.</h3><p>The OS is intended to be free. Hardware, model subscriptions or API usage, third-party licenses, and Maslow implementation services are separate.</p><Link href="/services">See how Maslow helps ↗</Link></article><article className={styles.row}><h3>Built on Omarchy.</h3><p>Maslow builds on Omarchy’s Linux desktop and customization foundations. Upstream projects retain their identities, licenses, and credits.</p><a href="https://omarchy.org/">Explore Omarchy ↗</a></article></div></section><NextStep title="Bring a task to the preview." body="Tell us about your hardware, the agents you use, and what you want to explore. We will discuss the current build and evaluation fit, or a workflow project on your existing systems." /></PageShell>; }
