import Link from "next/link";
import type { Metadata } from "next";
import { PageShell } from "@/components/layout/PageShell";
import { MarketingIntro, NextStep } from "@/components/marketing/Marketing";
import { StoryJourney } from "@/components/stories/StoryJourney";
import { manufacturingStory } from "@/lib/content/operating-stories";
import styles from "@/components/marketing/Marketing.module.css";
export const metadata: Metadata = { title: { absolute: "AI for Manufacturing Workflows | Maslow AI" }, description: "Explore drawing retrieval, quote preparation, and reporting, with source context and human review. See Maslow’s manufacturing client delivery experience.", alternates:{canonical:"/manufacturing"} };
export default function ManufacturingPage(){return <PageShell footer="full"><MarketingIntro eyebrow="FOR MANUFACTURING / BUILT AROUND THE WORK" title="Your know-how has more work to do." body="The right drawing. A comparable job. The numbers behind a quote. We help connect the information your experienced people need, so they can spend more time on the decisions that depend on them." secondaryHref="/case-studies/infinite-ai-os" secondaryLabel="See the manufacturing engagement" /><StoryJourney id="manufacturing-work" eyebrow="THREE TASKS TO EXPLORE" title="Follow the information to the decision." description="These are illustrative starting points for a scoped project. Sources, permissions, quality, and business value need to be tested with your team." variant="manufacturing" steps={manufacturingStory} afterHref="#client-work" afterLabel="See what we delivered" /><section className={styles.section} id="client-work"><p className="eyebrow">CLIENT ENGAGEMENT / INFINITE AI OS</p><h2>A foundation built with a manufacturing team.</h2><p>Our documented manufacturing engagement delivered a custom knowledge and workflow foundation, with four named agents responding in Microsoft Teams after the first 90 days. Connector hardening and operating-value measurement were separate workstreams.</p><p className={styles.note}>This custom client system is distinct from the free Maslow AI-OS Linux workspace. It demonstrates Maslow’s implementation experience, rather than what is included in an OS installation.</p><Link className="text-link" href="/case-studies/infinite-ai-os">Explore the scope, evidence, and remaining work ↗</Link></section><NextStep title="Bring the task your team knows too well." body="Start with a drawing search, a quote, a recurring report, or another point of friction. We can work on your existing infrastructure and agree on one useful test." /></PageShell>}
